#!/bin/sh

RPM=sbcl-1.0.38-3.el6.x86_64.rpm

# Make sure we have our lisp environment installed.
cd $OPENSHIFT_DATA_DIR
if ! test -f usr/bin/sbcl; then
    # It's not here.  Let's download and unpack it.
    curl -0 http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/x86_64/os/Packages/s/sbcl-1.1.8-1.fc20.x86_64.rpm > $RPM
    rpm2cpio $RPM | cpio -idmv
fi
