#!/bin/sh

# Initialize app
# 
# Invoke like so..
# 
# $ ./init-app
#

me=`echo "$0" | sed -e 's,.*/,,'`

usage="

Usage: $0

Run this script in the root directory of your openshift app's git repo.

Report bugs and patches to <green@spindazzle.org."

if test $# != 0; then
  echo "$0: too many arguments$usage" >&2
  exit 1
fi

if ! test -d diy; then
  echo "$0: missing diy directory$usage" >&2
  exit 1
fi

curl -O http://beta.quicklisp.org/quicklisp.lisp
HOME=`pwd` sbcl --load quicklisp.lisp --eval "(quicklisp-quickstart:install)" --eval "(quicklisp:quickload :hunchentoot)" --eval "(quit)"

cat > .openshift/action_hooks/pre_build <<EOF
#!/bin/sh
# Make sure we have decompressed the sbcl core file
cd \$OPENSHIFT_DATA_DIR
if test -f sbcl-dist.core.gz; then
  gzip -d sbcl-dist.core.gz
fi
if ! test -d sbcl-dist.core.gz; then
  mkdir cache
fi
EOF
chmod +x .openshift/action_hooks/pre_build

cat > .openshift/action_hooks/start <<EOF
#!/bin/sh
export XDG_CACHE_HOME=\${OPENSHIFT_DATA_DIR}/cache
cd \$OPENSHIFT_REPO_DIR
HOME=\`pwd\` SBCL_HOME=\`(cd ${OPENSHIFT_DATA_DIR}; pwd)\` nohup ${OPENSHIFT_DATA_DIR}/sbcl \
  --core ${OPENSHIFT_DATA_DIR}/sbcl-dist.core \
  --load ${OPENSHIFT_DATA_DIR}/asdf.fasl \
  --userinit ${OPENSHIFT_DATA_DIR}/sbclrc \
  --eval "(require :webapp)" --eval "(webapp:start-webapp)" > \${OPENSHIFT_LOG_DIR}/webapp.log 2>&1 &
EOF
chmod +x .openshift/action_hooks/start

cat > .openshift/action_hooks/build <<EOF
#!/bin/sh
export XDG_CACHE_HOME=\${OPENSHIFT_DATA_DIR}/cache
cd \${OPENSHIFT_REPO_DIR}
HOME=\`pwd\` SBCL_HOME=\${OPENSHIFT_DATA_DIR} \${OPENSHIFT_DATA_DIR}/sbcl --core \${OPENSHIFT_DATA_DIR}/sbcl-dist.core  --userinit \${OPENSHIFT_DATA_DIR}/sbclrc  --eval "(require :webapp)" --eval "(quit)"
EOF
chmod +x .openshift/action_hooks/build

cat > .openshift/action_hooks/stop <<EOF
#!/bin/sh
kill \`ps -ef | grep sbcl | grep -v grep | awk '{ print \$2 }'\` > /dev/null 2>&1
exit 0
EOF
chmod +x .openshift/action_hooks/stop

SRCDIR=`dirname $0`

cp $SRCDIR/*.lisp .
cp $SRCDIR/*.asd .

cat > .gitignore <<EOF
.cache
*~
EOF

git add .gitignore .openshift *
