#!/bin/sh

# Upload the sbcl binaries into your DIY OpenShift app.
# 
# Invoke like so..
# 
# $ ./upload-sbcl USER@APP-NAMESPACE.rhcloud.com APP
#
# In practice, this may look something like...
#
# $ ./upload-sbcl 8124934293249223492489e51abe28e4@myapp-mynamespace.rhcloud.com myapp
#
# The binaries are uploaded into your application's persistent 
# data directory.  You should only have to do this once.

me=`echo "$0" | sed -e 's,.*/,,'`

usage="

Usage: $0 USER@APP-NAMESPACE.rhcloud.com APP

Report bugs and patches to <green@moxielogic.com>."

if test $# != 2; then
  echo "$0: missing arguments$usage" >&2
  exit 1
fi

scp -r `dirname $0`/data $1:~/$2

